[colors.primary]
foreground = "#d3c6aa"
background = "#272e33"

[colors.normal]
black   = "#343f44"
red     = "#e67e80"
green   = "#a7c080"
yellow  = "#dbbc7f"
blue    = "#7fbbb3"
magenta = "#d699b6"
cyan    = "#83c092"
white   = "#859289"

[colors.bright]
black   = "#868d80"
red     = "#e67e80"
green   = "#a7c080"
yellow  = "#dbbc7f"
blue    = "#7fbbb3"
magenta = "#d699b6"
cyan    = "#83c092"
white   = "#9da9a0"
