[colors.primary]
foreground = "#C1C497"
background = "#111C18"

[colors.normal]
black   = "#23372B"
red     = "#FF5345"
green   = "#549E6A"
yellow  = "#459451"
blue    = "#509475"
magenta = "#D2689C"
cyan    = "#2DD5B7"
white   = "#F6F5DD"

[colors.bright]
black   = "#53685B"
red     = "#DB9F9C"
green   = "#143614"
yellow  = "#E5C736"
blue    = "#ACD4CF"
magenta = "#75BBB3"
cyan    = "#8CD3CB"
white   = "#9EEBB3"
