[colors.primary]
foreground = "#dee3e6"
background = "#0f1417"

[colors.normal]
black   = "#dee3e6"
red     = "#ffb4ab"
green   = "#dee3e6"
yellow  = "#aca98a"
blue    = "#89d0ed"
magenta = "#ffb4ab"
cyan    = "#dee3e6"
white   = "#f0f0f0"

[colors.bright]
black   = "#4c4c4c"
red     = "#c49ea0"
green   = "#9ec49f"
yellow  = "#c4c19e"
blue    = "#a39ec4"
magenta = "#c49ec4"
cyan    = "#9ec4c3"
white   = "#e7e7e7"
