[colors.primary]
foreground = "#eee0d4"
background = "#18120c"

[colors.normal]
black   = "#262626"
red     = "#ac8a8c"
green   = "#8aac8b"
yellow  = "#aca98a"
blue    = "#f7bb70"
magenta = "#ac8aac"
cyan    = "#8aacab"
white   = "#f0f0f0"

[colors.bright]
black   = "#4c4c4c"
red     = "#c49ea0"
green   = "#9ec49f"
yellow  = "#c4c19e"
blue    = "#a39ec4"
magenta = "#c49ec4"
cyan    = "#9ec4c3"
white   = "#e7e7e7"
