[colors.primary]
foreground = "#dde4e3"
background = "#0e1514"

[colors.normal]
black   = "#dde4e3"
red     = "#ffb4ab"
green   = "#dde4e3"
yellow  = "#aca98a"
blue    = "#80d5d3"
magenta = "#ffb4ab"
cyan    = "#dde4e3"
white   = "#f0f0f0"

[colors.bright]
black   = "#4c4c4c"
red     = "#c49ea0"
green   = "#9ec49f"
yellow  = "#c4c19e"
blue    = "#a39ec4"
magenta = "#c49ec4"
cyan    = "#9ec4c3"
white   = "#e7e7e7"
