[colors.primary]
foreground = "#161616"
background = "#f2f4f8"

[colors.normal]
black   = "#161616"
red     = "#3ddbd9"
green   = "#33b1ff"
yellow  = "#ee5396"
blue    = "#42be65"
magenta = "#be95ff"
cyan    = "#ff7eb6"
white   = "#f2f4f8"

[colors.bright]
black   = "#525252"
red     = "#3ddbd9"
green   = "#33b1ff"
yellow  = "#ee5396"
blue    = "#42be65"
magenta = "#be95ff"
cyan    = "#ff7eb6"
white   = "#ffffff"
