[colors.primary]
foreground = "#f8f8f2"
background = "#272822"

[colors.normal]
black   = "#272822"
red     = "#f92672"
green   = "#a6e22e"
yellow  = "#e6db74"
blue    = "#66d9ef"
magenta = "#fd971f"
cyan    = "#ae81ff"
white   = "#f8f8f2"

[colors.bright]
black   = "#75715e"
red     = "#f92672"
green   = "#a6e22e"
yellow  = "#e6db74"
blue    = "#66d9ef"
magenta = "#fd971f"
cyan    = "#ae81ff"
white   = "#f8f8f2"
