[colors.primary]
foreground = "{{colors.on_surface.default.hex}}"
background = "{{colors.background.default.hex}}"

[colors.normal]
black   = "{{colors.on_surface.default.hex}}"
red     = "{{colors.error.default.hex}}"
green   = "{{colors.on_surface.default.hex}}"
yellow  = "#aca98a"
blue    = "{{colors.primary.default.hex}}"
magenta = "{{colors.error.default.hex}}"
cyan    = "{{colors.on_surface.default.hex}}"
white   = "#f0f0f0"

[colors.bright]
black   = "#4c4c4c"
red     = "#c49ea0"
green   = "#9ec49f"
yellow  = "#c4c19e"
blue    = "#a39ec4"
magenta = "#c49ec4"
cyan    = "#9ec4c3"
white   = "#e7e7e7"
